export const featuredCategories = [
    {
        title: "Offers near you!",
        description: "Why not support your local restaurant tonight",
        id: 1
    },
    {
        title: "Fetured!",
        description: "Payed placements from our partners",
        id: 2
    },
    {
        title: "Tasty Discounts!",
        description: "Everyone's been enjoying these juicy discounts",
        id: 3
    },
]

export const featuredMenuCategories = [
    {
        name: "Ocean View",
        description: "Get your delicious and hot meals at the Ocean View restaurant. Have a good look at the beautiful ocean",
        image: require("./assets/res-16.jpg"),
        lat: 67.46477,
        lon: 114.78458,
        address: "GR8 Stoke Street",
        rating: 5,
        category: 1,
        id: 1,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 1,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 2,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 3,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 4,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 5, 
            },
        ]
    },
    {
        name: "The Palestine",
        description: "Get your delicious and hot meals at the Palestine restaurant. ",
        image: require("./assets/res-5.jpg"),
        lat: 41.06321,
        lon: -103.01914,
        address: "AP6 Sanity Street",
        rating: 4,
        category: 1,
        id: 2,
        dishes: [
            {
                ref: 1,
                image: require("./assets/dish-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal. Enjoy the African style.",
                name: "Fufu and Soup",
                price: 15,
                id: 6,
            },
            {
                ref: 1,
                image: require("./assets/dish-2.jpg"),
                name: "Banku and Tilapia",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious banku with grilled tilapia.",
                price: 18,
                id: 7,
            },
            {
                ref: 1,
                image: require("./assets/dish-3.jpg"),
                name: "Plantain and Stew",
                desc: "Delicious Plantain with Kontomire stew. Healthy and delicious.",
                price: 10,
                id: 8,
            },
            {
                ref: 1,
                image: require("./assets/dish-4.jpg"),
                name: "Jollof Rice",
                desc: "Enjoy the greate taste of jollof at it's finnest. Fresh riped plantain mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 9,
            },
            {
                ref: 1,
                image: require("./assets/dish-5.jpg"),
                name: "Boiled Yam",
                desc: "Enjoy the best boiled yam with tasty stew. You'll lick your fingers I promise.",
                price: 15,
                id: 10, 
            },
        ],
    },
    {
        name: "Break Fast ",
        description: "Take the edge of with the best breakfast around",
        image: require("./assets/res-4.jpg"),
        lat: -75.81226,
        lon: 28.96597,
        address: "PR25 Ocksland Street",
        rating: 5,
        category: 1,
        id: 3,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 11,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 12,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 13,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 14, 
            },
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 15,
            },
        ]
    },
    {
        name: "Fisher",
        description: "One stop shop for for fresh fried fishes",
        image: require("./assets/restaurant-2.jpg"),
        lat: 30.27721,
        lon: 50.69273,
        address: "AR12 Jake Street",
        rating: 5,
        category: 1,
        id: 4,
        dishes: [
            {
                ref: 1,
                image: require("./assets/dish-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal. Enjoy the African style.",
                name: "Fufu and Soup",
                price: 15,
                id: 16,
            },
            {
                ref: 1,
                image: require("./assets/dish-2.jpg"),
                name: "Banku and Tilapia",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious banku with grilled tilapia.",
                price: 18,
                id: 17,
            },
            {
                ref: 1,
                image: require("./assets/dish-3.jpg"),
                name: "Plantain and Stew",
                desc: "Delicious Plantain with Kontomire stew. Healthy and delicious.",
                price: 10,
                id: 18,
            },
            {
                ref: 1,
                image: require("./assets/dish-4.jpg"),
                name: "Jollof Rice",
                desc: "Enjoy the greate taste of jollof at it's finnest. Fresh riped plantain mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 19,
            },
            {
                ref: 1,
                image: require("./assets/dish-5.jpg"),
                name: "Boiled Yam",
                desc: "Enjoy the best boiled yam with tasty stew. You'll lick your fingers I promise.",
                price: 15,
                id: 20, 
            },
        ],
    },

    // second 
    {
        name: "The Caribbean",
        description: "Get your delicious and hot meals at the The Caribbean.",
        image: require("./assets/restaurant-3.jpg"),
        lat: 27.53843,
        lon: 103.93669,
        address: "CR8 Pirates Street",
        rating: 4,
        category: 2,
        id: 5,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 21,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 22,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 23,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 24,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 25, 
            },
        ]
    },
    {
        name: "Night Market",
        description: "Get your delicious and hot meals at the Night Market.",
        image: require("./assets/res-1.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "RA4 Golden Street",
        rating: 3,
        category: 2,
        id: 6,
        dishes: [
            {
                ref: 1,
                image: require("./assets/dish-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal. Enjoy the African style.",
                name: "Fufu and Soup",
                price: 15,
                id: 26,
            },
            {
                ref: 1,
                image: require("./assets/dish-2.jpg"),
                name: "Banku and Tilapia",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious banku with grilled tilapia.",
                price: 18,
                id: 27,
            },
            {
                ref: 1,
                image: require("./assets/dish-3.jpg"),
                name: "Plantain and Stew",
                desc: "Delicious Plantain with Kontomire stew. Healthy and delicious.",
                price: 10,
                id: 28,
            },
            {
                ref: 1,
                image: require("./assets/dish-4.jpg"),
                name: "Jollof Rice",
                desc: "Enjoy the greate taste of jollof at it's finnest. Fresh riped plantain mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 29,
            },
            {
                ref: 1,
                image: require("./assets/dish-5.jpg"),
                name: "Boiled Yam",
                desc: "Enjoy the best boiled yam with tasty stew. You'll lick your fingers I promise.",
                price: 15,
                id: 30, 
            },
        ],
    },
    {
        name: "Grimm",
        description: "Evenings are great at the grim. pay us a visit",
        image: require("./assets/res-8.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "GR4 Grimm Street",
        rating: 4,
        category: 2,
        id: 7,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 31,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 32,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 33,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 34,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 35, 
            },
        ]
    },

    // third
    {
        name: "Shelve Shift",
        description: "They always come back on the first try. This is your first time here? We look forward to a fruitful friendship with our delicious meals",
        image: require("./assets/res-6.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "CP8 Atlantic Street",
        rating: 5,
        category: 2,
        id: 8,
        dishes: [
            {
                ref: 1,
                image: require("./assets/dish-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal. Enjoy the African style.",
                name: "Fufu and Soup",
                price: 15,
                id: 36,
            },
            {
                ref: 1,
                image: require("./assets/dish-2.jpg"),
                name: "Banku and Tilapia",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious banku with grilled tilapia.",
                price: 18,
                id: 37,
            },
            {
                ref: 1,
                image: require("./assets/dish-3.jpg"),
                name: "Plantain and Stew",
                desc: "Delicious Plantain with Kontomire stew. Healthy and delicious.",
                price: 10,
                id: 38,
            },
            {
                ref: 1,
                image: require("./assets/dish-4.jpg"),
                name: "Jollof Rice",
                desc: "Enjoy the greate taste of jollof at it's finnest. Fresh riped plantain mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 39,
            },
            {
                ref: 1,
                image: require("./assets/dish-5.jpg"),
                name: "Boiled Yam",
                desc: "Enjoy the best boiled yam with tasty stew. You'll lick your fingers I promise.",
                price: 15,
                id: 40, 
            },
        ],
    },
    {
        name: "Light Haven",
        description: "Bring your loved ones to the light haven, you'll wish you did earlier",
        image: require("./assets/res-9.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "PR3 Stoke Street",
        rating: 4,
        category: 3,
        id: 9,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 41,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 42,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 43,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 44,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 45, 
            },
        ]
    },
    {
        name: "Mighty Stake",
        description: "Stakes are greate, but have you tried the ones at mighty stakes? It's about time you joined the club",
        image: require("./assets/res-10.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "MS6 Mass Street",
        rating: 5,
        category: 3,
        id: 10,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 46,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 47,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 48,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 49,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 50, 
            },
        ]
    },
    {
        name: "Blue Fill",
        description: "Get your delicious and hot meals at the Blue Fill.",
        image: require("./assets/res-11.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "PC8 Procto Street",
        rating: 4,
        category: 3,
        id: 11,
        dishes: [
            {
                ref: 1,
                image: require("./assets/dish-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal. Enjoy the African style.",
                name: "Fufu and Soup",
                price: 15,
                id: 51,
            },
            {
                ref: 1,
                image: require("./assets/dish-2.jpg"),
                name: "Banku and Tilapia",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious banku with grilled tilapia.",
                price: 18,
                id: 52,
            },
            {
                ref: 1,
                image: require("./assets/dish-3.jpg"),
                name: "Plantain and Stew",
                desc: "Delicious Plantain with Kontomire stew. Healthy and delicious.",
                price: 10,
                id: 53,
            },
            {
                ref: 1,
                image: require("./assets/dish-4.jpg"),
                name: "Jollof Rice",
                desc: "Enjoy the greate taste of jollof at it's finnest. Fresh riped plantain mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 54,
            },
            {
                ref: 1,
                image: require("./assets/dish-5.jpg"),
                name: "Boiled Yam",
                desc: "Enjoy the best boiled yam with tasty stew. You'll lick your fingers I promise.",
                price: 15,
                id: 55, 
            },
        ],
    },
    {
        name: "The Gladiators",
        description: "There's nothing like a good family re-union. The gladiators brings you close to loved ones.",
        image: require("./assets/res-12.jpg"),
        lat: 45.08343,
        lon: 35.3256,
        address: "BC5 Gladiators Street",
        rating: 4,
        category: 3,
        id: 12,
        dishes: [
            {
                ref: 1,
                image: require("./assets/asian-1.jpg"),
                desc: "Wow!!... This is delicious! That's what they all say. Enjoy your meal.",
                name: "Ribs Pate",
                price: 15,
                id: 56,
            },
            {
                ref: 1,
                image: require("./assets/asian-2.jpg"),
                name: "Chop Vite",
                desc: "Grab your chop sticks and join the ride. Tasty and delicious",
                price: 18,
                id: 57,
            },
            {
                ref: 1,
                image: require("./assets/asorted.jpg"),
                name: "Asorted Mix",
                desc: "Delicious mixed flavoured meat with fresh roughage. Healthy and delicious.",
                price: 20,
                id: 58,
            },
            {
                ref: 1,
                image: require("./assets/fish.jpg"),
                name: "Fish Salad",
                desc: "Fresh fish from deep waters mixed honey oil and flavoured fish sauce. Healthy and delicious.",
                price: 25,
                id: 59,
            },
            {
                ref: 1,
                image: require("./assets/vegan.jpg"),
                name: "Vegan Special",
                desc: "No meat no worries. You want vegan meals, we've got you covered. ",
                price: 15,
                id: 60, 
            },
        ]
    },

]


export const categories = [
    {
        title: "Caribbean",
        image: require("./assets/caribbean.jpg")
    },
    {
        title: "Exotic",
        image: require("./assets/exotic.jpg")
    },
    {
        title: "Asian",
        image: require("./assets/asian.jpg")
    },
    {
        title: "Local",
        image: require("./assets/cat-1.jpg")
    },
    {
        title: "Breakfast",
        image: require("./assets/fast.jpg")
    },
    {
        title: "Chinese",
        image: require("./assets/fish.jpg")
    },
]


